import ProgressBar from "@/components/ProgressBar/ProgressBar";
import Navbar from "@/components/ui/Navbar";
import { ChakraProvider } from "@chakra-ui/react";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
        <Navbar/>
        <ProgressBar/>
          {children}
          
          </ChakraProvider></body>
    </html>
  );
}
